### ISSUE TITLE
11.7 收藏其它项目

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#102]

**Comment by liujinmenghaoren** [comment]
![11 7](https://cloud.githubusercontent.com/assets/22046197/20347468/42a50c54-ac3c-11e6-8c5e-955b2590dd7d.png)

![11 7 2](https://cloud.githubusercontent.com/assets/22046197/20347543/9fa05f3a-ac3c-11e6-8f95-23a7d4b156af.png)

![11 7 3](https://cloud.githubusercontent.com/assets/22046197/20347545/a4800294-ac3c-11e6-91ae-c64ff1e56b59.png)

### 请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 👊
