### ISSUE TITLE
任务09. 在线学习 苏勇 Git 版本控制

### ISSUE THREAD

**Issue by liuxiumei123** [wangding/courses#113]
![image](https://cloud.githubusercontent.com/assets/23023584/20339124/9c267fb4-ac15-11e6-8091-a3f14f2eb5b6.png)

”请检查！“ @wangding

**Comment by wangding** [comment]
请贴上你的学习记录页面的截图啊

**Comment by liujinmenghaoren** [comment]
已检查，可以关闭了。
