### ISSUE TITLE
第十一周 任务6. Follow（关注）其他人

### ISSUE THREAD

**Issue by zhangmengyun** [wangding/courses#125]

**Comment by zhangmengyun** [comment]
![Uploading 火狐截图_2016-11-16T10-04-26.922Z.png…]()

@wangding

**Comment by wangding** [comment]
看不到图，请修改一下 🤕

**Comment by zhangmengyun** [comment]
![_2016-11-16t10-04-26 922z](https://cloud.githubusercontent.com/assets/23236431/20381728/a74521ce-ace3-11e6-83dc-2aab8956d0da.png)
@wangding

**Comment by wangding** [comment]
贴的图不对，这个图是我关注的人。你关注了谁呢？贴上图来，我看看啊。

**Comment by zhangmengyun** [comment]
![_2016-11-18t10-53-38 968z](https://cloud.githubusercontent.com/assets/23236431/20427764/89d3cb6c-adc0-11e6-8708-d84bb1240c2e.png)
@wangding

**Comment by wangding** [comment]
可以关闭了  👍
