### ISSUE TITLE
第十一周   任务09. 在线学习 苏勇 Git 版本控制

### ISSUE THREAD

**Issue by zhangmengyun** [wangding/courses#128]

**Comment by zhangmengyun** [comment]
![Uploading QQ截图20161116190206.png…]()

@wangding

**Comment by zhangmengyun** [comment]
![qq 20161116190206](https://cloud.githubusercontent.com/assets/23236431/20344924/a451b842-ac2f-11e6-8d62-d23998535df3.png)
@wangding

**Comment by wangding** [comment]
可以关闭了 👊
