### ISSUE TITLE
第十一周   任务10. 在线学习 深入理解 Git

### ISSUE THREAD

**Issue by zhangmengyun** [wangding/courses#129]

**Comment by zhangmengyun** [comment]
![qq 20161117163833](https://cloud.githubusercontent.com/assets/23236431/20382301/46199238-ace6-11e6-9627-34b087e3abdf.png)

![qq 20161117164009](https://cloud.githubusercontent.com/assets/23236431/20382319/58e3e9f4-ace6-11e6-9aad-09bd32c2ec1d.png)
![qq 20161117164045](https://cloud.githubusercontent.com/assets/23236431/20382332/614d7196-ace6-11e6-8c49-2ae1e2cc7c58.png)

@wangding

**Comment by wangding** [comment]
可以关闭了 👍
