### ISSUE TITLE
第十一周  任务12. 配置 Git

### ISSUE THREAD

**Issue by zhangmengyun** [wangding/courses#131]

**Comment by zhangmengyun** [comment]
![qq 20161122185824](https://cloud.githubusercontent.com/assets/23236431/20521348/ceb62d42-b0e5-11e6-8675-a890f1b74271.png)
@wangding

**Comment by wangding** [comment]
看一下已经关闭此任务的其他同学的截图

**Comment by zhangmengyun** [comment]
![qq 20161116181539](https://cloud.githubusercontent.com/assets/23236431/20953991/46e23e54-bc72-11e6-91ff-c83714fed25e.png)
@wangding

**Comment by zhangmengyun** [comment]
![qq 20161207114302](https://cloud.githubusercontent.com/assets/23236431/20954003/6e88c2ac-bc72-11e6-8bd0-a33f319a1a20.png)
@wangding

**Comment by liujinmenghaoren** [comment]
已检查，请及时关闭。
