### ISSUE TITLE
11.9 在线学习 苏勇git版本控制

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#136]

**Comment by liujinmenghaoren** [comment]
![11 9](https://cloud.githubusercontent.com/assets/22046197/20347998/80f294de-ac3e-11e6-8c20-b14596bb14d7.png)

### 已在线学习， 但是还要再认真学习一遍，请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 👍
