### ISSUE TITLE
11.10 在线学习 深入理解git

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#137]

**Comment by liujinmenghaoren** [comment]
![11 10](https://cloud.githubusercontent.com/assets/22046197/20348095/d73767a2-ac3e-11e6-8470-2645d34b692b.png)

### 已在线学习，但还需要认真学习一遍，请老师检查。 @wangding

**Comment by wangding** [comment]
> 已在线学习，但还需要认真学习一遍，请老师检查。

提醒一下啊，这个文字不应该格式化成标题，这是正文内容。
可以关闭了。

**Comment by liujinmenghaoren** [comment]
嗯，知道了老师，我以为这样会更明显一点。
