### ISSUE TITLE
11.11 安装git

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#138]
要求如下：
 下载git；下载地址为：http://rj.baidu.com/soft/detail/30195.html?ald
 安装完成后，在git bash运行git--version来验证安装是否成功；

**Comment by liujinmenghaoren** [comment]
![git](https://cloud.githubusercontent.com/assets/22046197/20347805/9a76c412-ac3d-11e6-964c-2a73c8a0703b.jpg)

### 已安装，请看，请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 👍
