### ISSUE TITLE
11.12 配置git

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#139]
要求如下：
 设置user name，注意次用户名应该是自己真实的中文名字；
 设置user email，注意此邮箱应该与GitHub的注册邮箱一致；

**Comment by liujinmenghaoren** [comment]
已配置，如下图，请老师见检查。
![git](https://cloud.githubusercontent.com/assets/22046197/20548022/1a6e1680-b15b-11e6-85f4-64b8ade4dc86.png)

**Comment by wangding** [comment]
可以关闭了 👍
