### ISSUE TITLE
任务6. Follow（关注）其他人

### ISSUE THREAD

**Issue by majianwei04** [wangding/courses#14]
浏览并关注王顶关注的人
或者自行在 Github 上浏览搜索，找到你感兴趣的并关注他

**Comment by liweiweiLWW** [comment]
已关注

**Comment by majianwei04** [comment]
![image](https://cloud.githubusercontent.com/assets/23111496/20288224/abcd94e8-ab0c-11e6-99b3-a53f12c0ffb7.png)
请检查

**Comment by wangding** [comment]
可以关闭了
