### ISSUE TITLE
11.13 在线练习git

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#140]
要求如下：
 在这里把git打通关；这里地址为：https://try.github.io/levels/1/challenges/1
 可以使用lantern代理；
 这个教学网站的用法，请看这里，网址为：https://github.com/wangding/courses/blob/master/github/images/try-git.png
 要求把这25关用到的命令记住并搞懂；

**Comment by liujinmenghaoren** [comment]
![default](https://cloud.githubusercontent.com/assets/22046197/20617992/736818b2-b327-11e6-9ec6-5914455d8e8e.png)
已通关，请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 💯
