### ISSUE TITLE
任务2. 注册 Github 账户 

### ISSUE THREAD

**Issue by gaoyang836** [wangding/courses#141]
要求如下：
实名注册；
用自己的真实照片，点亮头像；

**Comment by gaoyang836** [comment]
![default](https://cloud.githubusercontent.com/assets/23070667/20340042/8d9dd9ec-ac1a-11e6-8a54-b435a2d03d40.png)

**Comment by gaoyang836** [comment]
请检查        @liujinmenghaoren

**Comment by liujinmenghaoren** [comment]
### 嘿嘿，已经检查了，可以关闭喽~
