### ISSUE TITLE
 任务8. 测试 SeleniumIDEDoc 项目

### ISSUE THREAD

**Issue by gaoyang836** [wangding/courses#147]
要求如下：
    对该文档做静态检查
    如有错误，例如：错别字、翻译错误或语句不通顺，等。请在该项目的 issues 模块中提交 Labels（标记）为 bug 的 issue 。

**Comment by gaoyang836** [comment]
![8](https://cloud.githubusercontent.com/assets/23070667/20390241/f16bb072-ad08-11e6-8bdc-f52de4b178e3.png)

**Comment by gaoyang836** [comment]
请检查             @liujinmenghaoren

**Comment by wangding** [comment]
可以关闭了 👍
