### ISSUE TITLE
任务7. Star（收藏）其他项目

### ISSUE THREAD

**Issue by majianwei04** [wangding/courses#15]
浏览王顶收藏的项目，选择你感兴趣的项目收藏他
或者自行在 Github 上浏览搜索，选择你感兴趣的项目收藏他

**Comment by liweiweiLWW** [comment]
已收藏

**Comment by majianwei04** [comment]
![image](https://cloud.githubusercontent.com/assets/23111496/20288242/dac73236-ab0c-11e6-9208-3dffb619d8fe.png)
请检查

**Comment by wangding** [comment]
可以关闭了
