### ISSUE TITLE
11.14 本地练习git

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#156]
要求如下：
 在自己电脑的C盘根目录，建立文件夹：hello-git；
 在hello-git中初始化仓库；
 在hello-git中创建readme.md文件，文件内容随意；
 把readme.md文件提交到本地仓库中；
 在自己的GitHub账号中创建hello-git仓库；
 把自己本地的hello-git与远程的hello-git关联上；
 把百度搜索的自动化测试脚本search.html放到本地仓库hello-git中；
 把本地仓库中的内容push到远程hello-git中；
 在GitHub的hello-git仓库中，验证有两个文件存在，readme.md和search.html;

**Comment by liujinmenghaoren** [comment]
![_2016-11-25t08-20-59 901z](https://cloud.githubusercontent.com/assets/22046197/20618642/3e7cd9d6-b32b-11e6-9716-3bc0ff319fa8.png)
已完成，请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 🏃
