### ISSUE TITLE
11.15 动真格的

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#157]
要求如下：
 把自己以前创作的内容，放到 Github 托管起来；
 可以是自己的学习笔记
 可以是自己写过的代码
 可以是自己收集的网上的学习资源
 可以是自己写过的文档，注意，文档如果是 word 格式的，需要改成 MarkDown 格式的文档
 可以是......

**Comment by liujinmenghaoren** [comment]
![_2016-11-25t08-30-17 328z](https://cloud.githubusercontent.com/assets/22046197/20618893/7e962044-b32c-11e6-8ae2-01394ea5c6cd.png)
已完成，请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 👍
