### ISSUE TITLE
11.5Star（收藏）Selenium IDE项目

### ISSUE THREAD

**Issue by yulina0111** [wangding/courses#163]

**Comment by yulina0111** [comment]
![wangding seleniumidedoc selenium ide http www seleniumhq org docs 02_selenium_ide jsp](https://cloud.githubusercontent.com/assets/23208582/20453905/d9e03610-ae6d-11e6-9ea0-ae6c59017520.png)

**Comment by yulina0111** [comment]
请检查！ @wangding

**Comment by wangding** [comment]
可以关闭了 🐤
