### ISSUE TITLE
11.7 Star（收藏）其他项目

### ISSUE THREAD

**Issue by yulina0111** [wangding/courses#165]
要求如下：
浏览王顶收藏的项目，选择你感兴趣的项目收藏他
或者自行在 Github 上浏览搜索，选择你感兴趣的项目收藏他

**Comment by yulina0111** [comment]
![geeeeeeeeek electronic wechat a better wechat on macos and linux built with electron by zhongyi tong](https://cloud.githubusercontent.com/assets/23208582/20453930/97758680-ae6e-11e6-8163-5c9abb0966aa.png)

**Comment by yulina0111** [comment]
请检查！ @wangding

**Comment by wangding** [comment]
可以关闭了 🉑
