### ISSUE TITLE
[bug]语句不通顺

### ISSUE THREAD

**Issue by liweiweiLWW** [wangding/courses#17]
IDE的功能——>测试案例面板 中最后一句话（如下）不通顺。

如果你开始在命令字段键入命令，根据你键入的字符，会出现一个待选的命令下拉列表，您可以从中选择您想要命令。

建议修改：
当您在命令字段键入命令时，将会根据您已经键入的字符，出现一个待选的命令下拉列表，方便您从中选择想要的命令。

**Comment by wangding** [comment]
建议你把修改后的句子贴上来大家讨论一下啊。
