### ISSUE TITLE
11.15 动真格的

### ISSUE THREAD

**Issue by yulina0111** [wangding/courses#173]
要求如下：
把自己以前创作的内容，放到 Github 托管起来
可以是自己的学习笔记
可以是自己写过的代码
可以是自己收集的网上的学习资源
可以是自己写过的文档，注意，文档如果是 word 格式的，需要改成 MarkDown 格式的文档
可以是......

**Comment by yulina0111** [comment]
![4](https://cloud.githubusercontent.com/assets/23208582/20461453/e2be0f9c-af39-11e6-8b00-a900e35aa637.PNG)

**Comment by yulina0111** [comment]
请检查 @wangding

**Comment by wangding** [comment]
还没有动真格的啊，里面东西太少了
