### ISSUE TITLE
任务11. 安装 Git

### ISSUE THREAD

**Issue by majianwei04** [wangding/courses#174]
任务11. 安装 Git

要求如下：
从这里下载 Git
安装完成后，在 Git Bash 运行 git --version 来验证安装是否成功

**Comment by majianwei04** [comment]
![image](https://cloud.githubusercontent.com/assets/23111496/20373388/8c9b5320-acac-11e6-8d98-517f4388981b.png)
请检查

**Comment by wangding** [comment]
可以关闭了 👍
