### ISSUE TITLE
任务12. 配置 Git

### ISSUE THREAD

**Issue by majianwei04** [wangding/courses#176]
任务12. 配置 Git

要求如下：
设置 user.name，注意此用户名应该是自己真实的中文姓名
设置 user.email，注意此 email 应该和 github 的注册邮箱相同

**Comment by majianwei04** [comment]
![image](https://cloud.githubusercontent.com/assets/23111496/20373634/145d2b98-acae-11e6-97ed-1f8007877c22.png)
请检查

**Comment by majianwei04** [comment]
![image](https://cloud.githubusercontent.com/assets/23111496/20373743/d94ca30c-acae-11e6-955a-76985b782c14.png)
请检查

**Comment by wangding** [comment]
可以关闭了 👊
