### ISSUE TITLE
任务09. 在线学习 苏勇 Git 版本控制

### ISSUE THREAD

**Issue by diruixin** [wangding/courses#177]
任务09. 在线学习 [苏勇 Git 版本控制](http://edu.51cto.com/course/course_id-1412.html)

**Comment by diruixin** [comment]
![task9](https://cloud.githubusercontent.com/assets/23021982/20378034/7b3ee548-acce-11e6-9c35-0572505eb22c.png)
学习完成。

**Comment by wangding** [comment]
可以关闭了 🉑
