### ISSUE TITLE
任务11. 安装 Git

### ISSUE THREAD

**Issue by diruixin** [wangding/courses#179]
要求如下：

- 下载 Git
- 安装完成后，在 Git Bash 运行 git --version 来验证安装是否成功

**Comment by diruixin** [comment]
![task11](https://cloud.githubusercontent.com/assets/23021982/20378251/c8690a64-accf-11e6-89f5-cacee693b15c.png)
已安装，且验证安装成功。

**Comment by wangding** [comment]
可以关闭了 💯
