### ISSUE TITLE
[bug]语句不通顺

### ISSUE THREAD

**Issue by liweiweiLWW** [wangding/courses#18]
制作测试案例——>录制  最后
![image](https://cloud.githubusercontent.com/assets/23024716/20256041/04be504c-aa7c-11e6-9c83-6a5923f87e75.png)

建议修改：
type命令：点击网页的某些区域时才能录制

**Comment by wangding** [comment]
最好给出修改后的句子，这样咱们可以讨论一下。另外，这个 bug 应该提在 SeleniumIDEDoc 仓库下面。
