### ISSUE TITLE
任务12. 配置 Git

### ISSUE THREAD

**Issue by diruixin** [wangding/courses#180]
要求如下：

- 设置 user.name，注意此用户名应该是自己真实的中文姓名
- 设置 user.email，注意此 email 应该和 github 的注册邮箱相同

**Comment by diruixin** [comment]
![task12](https://cloud.githubusercontent.com/assets/23021982/20378271/e9596282-accf-11e6-923f-72a7186c54bf.png)
配置成功。

**Comment by wangding** [comment]
可以关闭了 👍
