### ISSUE TITLE
 任务10. 在线学习 深入理解 Git

### ISSUE THREAD

**Issue by diruixin** [wangding/courses#181]
任务10. 在线学习 [深入理解 Git](http://edu.51cto.com/course/course_id-1838.html)

**Comment by diruixin** [comment]
已完成40%。

**Comment by diruixin** [comment]
由于在线视频比较卡顿，所以同时结合了文字版的git教程。目前已完成大概80%左右，对应视频的大纲，还有commit对象和tree-ish表达式两个课时没有学习。

**Comment by diruixin** [comment]
已完成

**Comment by wangding** [comment]
可以关闭了 💯
