### ISSUE TITLE
 任务13. 在线练习 Git

### ISSUE THREAD

**Issue by diruixin** [wangding/courses#182]
要求如下：

- 在 [这里](https://try.github.io/levels/1/challenges/1) 把 Git 打通关
- 如果在线练习 Git 的网站打开速度很慢，请使用 Lantern 代理
- 这个在线教学网站的用法，请查看这里
- 要求把这 25 关用到的命令记住，并搞明白，不明白的地方可以百度，或者查阅 Pro Git 电子书

**Comment by yulina0111** [comment]
![22](https://cloud.githubusercontent.com/assets/23208582/20460924/11f81a58-af2d-11e6-8a69-1e2d46fb7330.PNG)
