### ISSUE TITLE
任务15. 动真格的

### ISSUE THREAD

**Issue by diruixin** [wangding/courses#184]
要求如下：

- 把自己以前创作的内容，放到 Github 托管起来
- 可以是自己的学习笔记
- 可以是自己写过的代码
- 可以是自己收集的网上的学习资源
- 可以是自己写过的文档，注意，文档如果是 word 格式的，需要改成 MarkDown 格式的文档
- 可以是......

**Comment by diruixin** [comment]
![task15](https://cloud.githubusercontent.com/assets/23021982/20506160/fd503016-b08c-11e6-8408-1bb0bd88b655.png)
已建立myStudy仓库，收藏了一些产品的资料和部分git学习笔记

**Comment by wangding** [comment]
可以关闭了 👍
