### ISSUE TITLE
任务2. 注册 Github 账户 

### ISSUE THREAD

**Issue by diruixin** [wangding/courses#2]
[参考视频](images/joinGithub.gif)
要求如下：
实名注册；
用自己的真实照片，点亮头像；

**Comment by diruixin** [comment]
![diruixin_github](https://cloud.githubusercontent.com/assets/23021982/20252045/999eb814-aa59-11e6-9fe9-095c430fe06f.png)
请检查

**Comment by wangding** [comment]
可以关闭了。
