### ISSUE TITLE
在线练习git

### ISSUE THREAD

**Issue by caokaixuan** [wangding/courses#205]
要求如下：
在这里把 Git 打通关
如果在线练习 Git 的网站打开速度很慢，请使用 Lantern 代理
这个在线教学网站的用法，请查看这里
要求把这 25 关用到的命令记住，并搞明白，不明白的地方可以百度，或者查阅 Pro Git 电子书

**Comment by caokaixuan** [comment]
![index](https://cloud.githubusercontent.com/assets/23349004/20430279/66373280-adce-11e6-89a8-f02ec00e808d.png)
@wangding

**Comment by wangding** [comment]
可以关闭了  👍
