### ISSUE TITLE
 任务2. 注册 Github 账户

### ISSUE THREAD

**Issue by durenshuanga** [wangding/courses#208]
参考视频，  要求如下：
    实名注册；
    用自己的真实照片，点亮头像

**Comment by durenshuanga** [comment]
![_2016-11-20t05-09-26 785z](https://cloud.githubusercontent.com/assets/23350302/20460599/ade67c76-af22-11e6-99ce-5a9fa44f50a3.png)
@wangding 
请检查！

**Comment by lilizhiwei** [comment]
已检查，可以关闭了
