### ISSUE TITLE
任务11. 安装 Git

### ISSUE THREAD

**Issue by durenshuanga** [wangding/courses#217]
要求如下：
    下载 Git
    安装完成后，在 Git Bash 运行 git --version 来验证安装是否成功

**Comment by durenshuanga** [comment]
![default](https://cloud.githubusercontent.com/assets/23350302/20527949/3dcfe0be-b105-11e6-8f0f-e3530f2a45b7.PNG)
@wangding 
请检查！

**Comment by wangding** [comment]
可以关闭了 🉑
