### ISSUE TITLE
任务2. 注册 Github 账户

### ISSUE THREAD

**Issue by shentong950228** [wangding/courses#223]
o	参考视频
o	要求如下：
o	实名注册；
o	用自己的真实照片，点亮头像；

**Comment by shentong950228** [comment]
![default](https://cloud.githubusercontent.com/assets/23491775/20473568/8e5169b8-affc-11e6-8332-4f968f569f14.png)

**Comment by lilizhiwei** [comment]
已检查，可以关闭了
