### ISSUE TITLE
 任务6. Follow（关注）其他人

### ISSUE THREAD

**Issue by shentong950228** [wangding/courses#227]
要求如下：
浏览并关注王顶关注的人
或者自行在 Github 上浏览搜索，找到你感兴趣的并关注他

**Comment by shentong950228** [comment]
![following](https://cloud.githubusercontent.com/assets/23491775/20473708/66cb7662-affd-11e6-9292-0bef98ed1779.png)

**Comment by lilizhiwei** [comment]
已检查，可以关闭了
