### ISSUE TITLE
 任务7. Star（收藏）其他项目

### ISSUE THREAD

**Issue by shentong950228** [wangding/courses#228]
o	要求如下：
o	浏览王顶收藏的项目，选择你感兴趣的项目收藏他
o	或者自行在 Github 上浏览搜索，选择你感兴趣的项目收藏他

**Comment by shentong950228** [comment]
![stars](https://cloud.githubusercontent.com/assets/23491775/20473745/ab152b60-affd-11e6-9270-5af4d9aa57eb.png)

**Comment by lilizhiwei** [comment]
已检查，可以关闭了
