### ISSUE TITLE
任务11. 安装 Git

### ISSUE THREAD

**Issue by shentong950228** [wangding/courses#232]
o	要求如下：
o	从这里下载 Git
o	安装完成后，在 Git Bash 运行 git --version 来验证安装是否成功

**Comment by shentong950228** [comment]
![git bash](https://cloud.githubusercontent.com/assets/23491775/20524277/b1a4c934-b0f4-11e6-900e-f7cc786e8801.png)

**Comment by wangding** [comment]
可以关闭了 🐤
