### ISSUE TITLE
任务12. 配置 Git

### ISSUE THREAD

**Issue by shentong950228** [wangding/courses#233]
o	要求如下：
o	设置 user.name，注意此用户名应该是自己真实的中文姓名
o	设置 user.email，注意此 email 应该和 github 的注册邮箱相同

**Comment by shentong950228** [comment]
![default](https://cloud.githubusercontent.com/assets/23491775/20548141/eac5c2ce-b15b-11e6-9e78-e7f320651d7a.png)

**Comment by wangding** [comment]
可以关闭了 🉑
