### ISSUE TITLE
任务13. 在线练习 Git

### ISSUE THREAD

**Issue by shentong950228** [wangding/courses#234]
o	要求如下：
o	在这里把 Git 打通关
o	如果在线练习 Git 的网站打开速度很慢，请使用 Lantern 代理
o	这个在线教学网站的用法，请查看这里
o	要求把这 25 关用到的命令记住，并搞明白，不明白的地方可以百度，或者查阅 Pro Git 电子书

**Comment by shentong950228** [comment]
![default](https://cloud.githubusercontent.com/assets/23491775/20524233/7d71e250-b0f4-11e6-895e-2c930eab9b3b.png)

**Comment by wangding** [comment]
可以关闭了 💯
