### ISSUE TITLE
任务3. Follow（关注）王顶

### ISSUE THREAD

**Issue by gaomengyao** [wangding/courses#24]
请检查 @wangding

**Comment by wangding** [comment]
查看一下已经关闭的 issue，参考一下别人提交的问题啊。:smile:

**Comment by gaomengyao** [comment]
![default](https://cloud.githubusercontent.com/assets/23348985/20304917/b3d677fc-ab6d-11e6-8503-b59c85585258.png)

**Comment by wangding** [comment]
可以关闭了，图片能清楚一点儿就更好了。 :star2:
