### ISSUE TITLE
第十三周任务四：继续完善软件测试课程学习笔记的思维导图

### ISSUE THREAD

**Issue by zhangmengyun** [wangding/courses#258]

**Comment by zhangmengyun** [comment]
[http://www.processon.com/mindmap/583bef9de4b08e31355919df](url)

**Comment by zhangmengyun** [comment]
@wangding

**Comment by liujinmenghaoren** [comment]
网址打不开，请确认后再次提交。

**Comment by zhangmengyun** [comment]
[https://www.processon.com/mindmap/583bef9de4b08e31355919df](url)
@wangding

**Comment by zhangmengyun** [comment]
[https://www.processon.com/view/581af62de4b021bdce47c691](url)
@wangding

**Comment by liujinmenghaoren** [comment]
已检查，请及时关闭。
