### ISSUE TITLE
 任务11. 安装 Git

### ISSUE THREAD

**Issue by gaomengyao** [wangding/courses#32]
要求如下：
    从这里   http://rj.baidu.com/soft/detail/30195.html?ald  下载 Git
    安装完成后，在 Git Bash 运行 git --version 来验证安装是否成功

**Comment by gaomengyao** [comment]
请检查 @wangding 
![3](https://cloud.githubusercontent.com/assets/23348985/20342837/f9ae9444-ac26-11e6-9404-166236372e9d.png)

**Comment by wangding** [comment]
可以关闭了 👍
