### ISSUE TITLE
13.2 仔细阅读教材第八章和第九章内容，并继续完善脑图

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#336]

**Comment by liujinmenghaoren** [comment]
已阅读课本并完成脑图，查看地址为： https://www.processon.com/view/58296dffe4b0fa6ffbcd61e2
因为processon近期不太稳定，所以本周部分是在百度脑图上做的，加了链接。
下面是百度脑图的地址链接：http://naotu.baidu.com/file/2a6fc6a9aabd003860997acd4f551495?token=2020a42b38f23039
请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 💯
