### ISSUE TITLE
13.4 提交黑盒测试案例结果

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#338]
在 github 的问题描述或者问题更新的描述中，以表格的方式任务13.3所有设计好的测试案例。
    请注意问题描述中表格的格式要求，表格的行数取决于测试案例的数量，表格的列数必须和问题模板的列数一致

**Comment by liujinmenghaoren** [comment]
![13 4](https://cloud.githubusercontent.com/assets/22046197/20656252/ab39302e-b565-11e6-95b2-30dd145e4900.png)
上面截图是测试用例的列表，请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 👊
