### ISSUE TITLE
13.5 执行测试并提交bug

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#339]
###  执行测试
用任务13.3,13.4设计好的测试案例来执行测试
用 Selenium IDE 制作自动化测试脚本，进行自动化测试
注意，请用下面的测试账户来录制自动化测试脚本：
登录邮箱：wangding@chmiot.net
登录密码：Passw0rd!
将制作好的自动化测试脚本，作为附件提交在 github 的 issue 中
### 提交bug
请将执行测试中发现的 bug，在 github 中提交问题，在问题描述中对 bug 进行描述，一个 bug 一个 issue 。

**Comment by liujinmenghaoren** [comment]
由于 issues 不支持测试脚本格式，便把测试脚本放在了自己的 github 仓库中，下面是链接地址： https://github.com/liujinmenghaoren/selenium-IDE
请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 👍
