### ISSUE TITLE
任务13. 在线练习 Git

### ISSUE THREAD

**Issue by gaomengyao** [wangding/courses#34]
要求如下：
    在这里把 Git 打通关
    如果在线练习 Git 的网站打开速度很慢，请使用 Lantern 代理
    这个在线教学网站的用法，请查看这里https://github.com/wangding/courses/blob/master/github/images/try-git.png
    要求把这 25 关用到的命令记住，并搞明白，不明白的地方可以百度，或者查阅 Pro Git 电子书https://git-scm.com/book/zh/v2

**Comment by gaomengyao** [comment]
@wangding  请检查：
![default](https://cloud.githubusercontent.com/assets/23348985/20417713/5b1e7a12-ad82-11e6-8052-1859dcf7b0c9.png)

**Comment by wangding** [comment]
可以关闭了 👍
