### ISSUE TITLE
13.7 提交黑盒测试案例结果

### ISSUE THREAD

**Issue by lilizhiwei** [wangding/courses#355]

**Comment by lilizhiwei** [comment]
测试用例上部分
![1](https://cloud.githubusercontent.com/assets/22817699/20641370/758878ca-b431-11e6-89aa-00b023b6e496.png)

**Comment by lilizhiwei** [comment]
已完成，请检查
@wangding 
![1](https://cloud.githubusercontent.com/assets/22817699/20647103/32fbfdfc-b4c6-11e6-9fbf-e3a495881a91.png)

**Comment by wangding** [comment]
可以关闭了 :smile:
