### ISSUE TITLE
任务15. 动真格的

### ISSUE THREAD

**Issue by gaomengyao** [wangding/courses#36]
要求如下：
    把自己以前创作的内容，放到 Github 托管起来
    可以是自己的学习笔记
    可以是自己写过的代码
    可以是自己收集的网上的学习资源
    可以是自己写过的文档，注意，文档如果是 word 格式的，需要改成 MarkDown 格式的文档
    可以是......

**Comment by gaomengyao** [comment]
上传到了hello-git仓库（12.15），请检查：   https://github.com/gaomengyao/hello-git
@wangding

**Comment by wangding** [comment]
可以关闭了
