### ISSUE TITLE
在线学习 Selenium IDE WEB 自动化测试（下）

### ISSUE THREAD

**Issue by zhangmengyun** [wangding/courses#378]

**Comment by zhangmengyun** [comment]
![qq 20161204184553](https://cloud.githubusercontent.com/assets/23236431/20871984/e2f1f7b0-bad5-11e6-915d-b150a08e38a7.png)
![qq 20161205102940](https://cloud.githubusercontent.com/assets/23236431/20871986/e727c756-bad5-11e6-8b4e-525a98336540.png)
@wangding

**Comment by wangding** [comment]
可以关闭了
