### ISSUE TITLE
12.4    Star（收藏）courses 项目

### ISSUE THREAD

**Issue by duqiaoyu** [wangding/courses#40]
![star](https://cloud.githubusercontent.com/assets/23206691/20796370/cf645eda-b810-11e6-92de-a7272255d220.png)
已完成，请老师检查！@wangding

**Comment by duqiaoyu** [comment]
![star](https://cloud.githubusercontent.com/assets/23206691/20796370/cf645eda-b810-11e6-92de-a7272255d220.png)
已完成，请老师检查！@wangding

**Comment by wangding** [comment]
可以关闭了 👍
