### ISSUE TITLE
12.5   Star（收藏）SeleniumIDEDoc 项目

### ISSUE THREAD

**Issue by duqiaoyu** [wangding/courses#41]
![star1](https://cloud.githubusercontent.com/assets/23206691/20796507/65da89a2-b811-11e6-81b6-d5d34b7a38ab.png)
已完成，请老师检查！@wangding

**Comment by duqiaoyu** [comment]
![star1](https://cloud.githubusercontent.com/assets/23206691/20796507/65da89a2-b811-11e6-81b6-d5d34b7a38ab.png)
已完成，请老师检查！@wangding

**Comment by wangding** [comment]
可以关闭了 💯
