### ISSUE TITLE
12.7   Star（收藏）其他项目

### ISSUE THREAD

**Issue by duqiaoyu** [wangding/courses#43]
要求如下：
    浏览王顶收藏的项目，选择你感兴趣的项目收藏他
    或者自行在 Github 上浏览搜索，选择你感兴趣的项目收藏他

https://github.com/duqiaoyu?tab=stars
已完成，请老师检查！@wangding

**Comment by duqiaoyu** [comment]
https://github.com/duqiaoyu?tab=stars
已完成，请老师检查！@wangding

**Comment by liujinmenghaoren** [comment]
已检查，请及时关闭。
