### ISSUE TITLE
14.3 制作自动化测试脚本，并提交至远程仓库selenium

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#437]
需要制作的自动化脚本有：
1. 手机归属地查询；
2. 弹框；
3. 时间校准网；
4. 两数求和；
5. locator参数化；
6. 自定义扩展；
7. 百度首页；
8. 四个网站的js DDT；
9. 四个网站的cvs DDT;
10. 四个网站的xml DDT；

**Comment by liujinmenghaoren** [comment]
脚本及相关文件已经上传至github的仓库中，查看地址为：https://github.com/liujinmenghaoren/selenium
其中sample, 14case, js, csv, xml 文件夹是本次作业结果。
请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 👍
