### ISSUE TITLE
12.11    安装 Git

### ISSUE THREAD

**Issue by duqiaoyu** [wangding/courses#47]
要求如下：
    从这里下载 Git
    安装完成后，在 Git Bash 运行 git --version 来验证安装是否成功

![git anzhuang](https://cloud.githubusercontent.com/assets/23206691/20796790/c0f65b76-b812-11e6-85a3-f0738a30d547.png)

已完成，请老师检查！@wangding

**Comment by duqiaoyu** [comment]
![git anzhuang](https://cloud.githubusercontent.com/assets/23206691/20796790/c0f65b76-b812-11e6-85a3-f0738a30d547.png)

已完成，请老师检查！@wangding

**Comment by wangding** [comment]
可以关闭了 🉑
