### ISSUE TITLE
12.12    配置 Git

### ISSUE THREAD

**Issue by duqiaoyu** [wangding/courses#48]
要求如下：
    设置 user.name，注意此用户名应该是自己真实的中文姓名
    设置 user.email，注意此 email 应该和 github 的注册邮箱相同

![git](https://cloud.githubusercontent.com/assets/23206691/20797277/0acc226a-b815-11e6-8b38-373e233b971a.png)
已完成，请老师检查！@wangding

**Comment by duqiaoyu** [comment]
![git](https://cloud.githubusercontent.com/assets/23206691/20797277/0acc226a-b815-11e6-8b38-373e233b971a.png)
已完成，请老师检查！@wangding

**Comment by wangding** [comment]
请运行 git config --list 命令，并截图
