### ISSUE TITLE
12.13   在线练习 Git

### ISSUE THREAD

**Issue by duqiaoyu** [wangding/courses#49]
要求如下：
    在这里把 Git 打通关
    如果在线练习 Git 的网站打开速度很慢，请使用 Lantern 代理
    这个在线教学网站的用法，请查看这里
    要求把这 25 关用到的命令记住，并搞明白，不明白的地方可以百度，或者查阅 Pro Git 电子书

   ![git](https://cloud.githubusercontent.com/assets/23206691/20858397/2874ee62-b97f-11e6-8024-a6fae1419f01.png)
   https://try.github.io/levels/1/challenges/25 
   已完成，请老师检查 @wangding

**Comment by duqiaoyu** [comment]
![git](https://cloud.githubusercontent.com/assets/23206691/20858397/2874ee62-b97f-11e6-8024-a6fae1419f01.png)
   https://try.github.io/levels/1/challenges/25 
   已完成，请老师检查 @wangding
   通关已打完，但命令还没完全掌握，需在练习

**Comment by wangding** [comment]
可以关闭了 🐤
