### ISSUE TITLE
12.14    本地练习 Git

### ISSUE THREAD

**Issue by duqiaoyu** [wangding/courses#50]
要求如下：
    在自己电脑的 C： 盘根目录，建立 文件夹：hello-git
    在 hello-git 中初始化仓库
    在 hello-git 中创建 README.md 文件，文件内容随意
    把 README.md 文件，提交到本地仓库中
    在自己的 Github 账户中创建 hello-git 仓库，注意照此截图操作
    把自己本地的 hello-git 仓库与远程的（上一步创建的）hello-git 仓库关联上
    把百度搜索的 Selenium IDE 自动化脚本 search.html，放到本地 hello-git 仓库中
    把本地的 hello-git 仓库中的内容 push（同步）到远程 hello-git 仓库中
    在 Github 的 hello-git 仓库中，验证有两个文件存在：README.md 和 search.html

**Comment by duqiaoyu** [comment]
https://github.com/duqiaoyu/hello-git
已完成，请老师检查！@wangding

**Comment by wangding** [comment]
可以关闭了 👍
