### ISSUE TITLE
14 任务9 制作两数求和自动化测试脚本

### ISSUE THREAD

**Issue by gaoyang836** [wangding/courses#529]

**Comment by gaoyang836** [comment]
https://github.com/gaoyang836/seleniumIDE/tree/master/seIDE

**Comment by gaoyang836** [comment]
请检查 @liujinmenghaoren

**Comment by liujinmenghaoren** [comment]
![_2016-12-13t02-05-20 258z](https://cloud.githubusercontent.com/assets/22046197/21124754/c6b0152c-c11b-11e6-9615-255048a354a7.png)
没见啊？哪个是？
