### ISSUE TITLE
任务2. 注册 Github 账户 

### ISSUE THREAD

**Issue by wangxiaoning1** [wangding/courses#53]
参考视频
    要求如下：
    实名注册；
    用自己的真实照片，点亮头像；

**Comment by wangxiaoning1** [comment]
![default](https://cloud.githubusercontent.com/assets/23205657/20333949/4d048c4c-abf1-11e6-8666-8ddf830a4ce3.PNG)
@wangding

**Comment by wangding** [comment]
可以关闭了 👍
