### ISSUE TITLE
第十五周任务七：整理手机硬件配置清单

### ISSUE THREAD

**Issue by zhangmengyun** [wangding/courses#558]

**Comment by zhangmengyun** [comment]
![qq 20161209170850](https://cloud.githubusercontent.com/assets/23236431/21043534/4e41e6ba-be32-11e6-8e65-b77e344ea0cd.png)
@wangding

**Comment by zhangmengyun** [comment]
![qq 20161209170850](https://cloud.githubusercontent.com/assets/23236431/21043534/4e41e6ba-be32-11e6-8e65-b77e344ea0cd.png)
@wangding

**Comment by wangding** [comment]
可以关闭了 👍
