### ISSUE TITLE
 任务09. 在线学习 苏勇 Git 版本控制

### ISSUE THREAD

**Issue by wangxiaoning1** [wangding/courses#60]

**Comment by wangxiaoning1** [comment]
![_2016-11-19t14-16-07 574z](https://cloud.githubusercontent.com/assets/23205657/20456029/c9ac8e00-aea5-11e6-9c69-be08fd14ba45.png)
@wangding 
请检查！！！

**Comment by wangxiaoning1** [comment]
![_2016-11-23t00-41-24 270z](https://cloud.githubusercontent.com/assets/23205657/20547696/e8a43e10-b158-11e6-8889-b60adf62f72d.png)
@wangding 
请检查！！！

**Comment by wangding** [comment]
可以关闭了 👍
