### ISSUE TITLE
 任务11. 安装 Git

### ISSUE THREAD

**Issue by wangxiaoning1** [wangding/courses#62]
要求如下：
    从这里下载 Git
    安装完成后，在 Git Bash 运行 git --version 来验证安装是否成功

**Comment by wangxiaoning1** [comment]
![default](https://cloud.githubusercontent.com/assets/23205657/20455510/648f35c0-ae98-11e6-960b-a1d4f086bb07.PNG)
@wangding 
请检查！！！

**Comment by lilizhiwei** [comment]
已检查，可以关闭了
