### ISSUE TITLE
15.3 整理手机硬件配置清单

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#653]
以表格的方式呈现。

**Comment by liujinmenghaoren** [comment]
![default](https://cloud.githubusercontent.com/assets/22046197/21041289/06f63156-be25-11e6-9ebe-0854543eba67.png)
已经把同学们的手机配置信息整理成表格，个别信息缺失。
 @wangding 请老师检查。

**Comment by wangding** [comment]
可以关闭了 👍
