### ISSUE TITLE
15.4 整理电脑硬件的配置清单

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#654]
以表格的形式呈现。

**Comment by liujinmenghaoren** [comment]
![default](https://cloud.githubusercontent.com/assets/22046197/21077408/669f750c-bf85-11e6-9c96-a2e91ccc6ea1.png)
已整理，如上图，请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 👍
