### ISSUE TITLE
15.5 对手机和电脑做等价类划分

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#656]
用脑图呈现。

**Comment by liujinmenghaoren** [comment]
已整理脑图，查看地址为：https://www.processon.com/view/584922eae4b005d48b67a2cd
请老师检查。 @wangding

**Comment by wangding** [comment]
等价类划分中，品牌不是主要参数，把这个从图中去掉，再改进一下啊

**Comment by liujinmenghaoren** [comment]
重新修改脑图，查看地址为： https://www.processon.com/view/584922eae4b005d48b67a2cd
请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 👍
