### ISSUE TITLE
15.6 对testin网站进行探索

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#659]
1. 了解网站功能；
2. 将百度网盘APP上传到testin网站进行测试；
3. 汇报测试结果；
4. 总结使用体验；

**Comment by liujinmenghaoren** [comment]
已完成，检查地址为：https://github.com/liujinmenghaoren/myTest/tree/master/testin
   请老师检查。 @wangding

**Comment by liujinmenghaoren** [comment]
地址依旧，请老师再检查一遍。 @wangding

**Comment by wangding** [comment]
可以关闭了 👍

**Comment by liujinmenghaoren** [comment]
嗯嗯
