### ISSUE TITLE
任务6. Follow（关注）其他人

### ISSUE THREAD

**Issue by diruixin** [wangding/courses#8]
要求如下：

- 浏览并关注王顶关注的人
- 或者自行在 Github 上浏览搜索，找到你感兴趣的并关注他

**Comment by liweiweiLWW** [comment]
已关注

**Comment by diruixin** [comment]
![task6](https://cloud.githubusercontent.com/assets/23021982/20378122/fe8e91f0-acce-11e6-90fc-1312918bd14d.png)
已完成

**Comment by wangding** [comment]
可以关闭了 ⚙
