### ISSUE TITLE
11.2 注册Github账户

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#84]
要求如下：
 实名注册；
 用自己的真是照片点亮头像；

**Comment by liujinmenghaoren** [comment]
![git](https://cloud.githubusercontent.com/assets/22046197/20340072/b466ace8-ac1a-11e6-9b50-c0e79d7b5ed6.jpg)

### 已有账号，如上图，请老师检查。 @wangding

**Comment by wangding** [comment]
可以关闭了 🉑
