### ISSUE TITLE
11-2.注册Github账户

### ISSUE THREAD

**Issue by zhaomengmenga** [wangding/courses#89]

**Comment by zhaomengmenga** [comment]
![_2016-12-14t03-51-24 528z](https://cloud.githubusercontent.com/assets/23491615/21169054/d5ca006c-c1f3-11e6-82f1-6eed1d5b0ff3.png)
@lilizhiwei

**Comment by zhaomengmenga** [comment]
请检查

**Comment by wangding** [comment]
你截的图有问题，看一下别的同学截的图。修改一下啊！~
