### ISSUE TITLE
git log命令提示错误

### ISSUE THREAD

**Issue by TristanChow** [wangding/courses#902]
王老师，请问下我在git bush git log命令怎么会提示错误：
![default](https://cloud.githubusercontent.com/assets/22495404/25141138/340b2788-2495-11e7-8ef8-bcb5541c3920.png)

**Comment by wangding** [comment]
下面的英文信息写的很清楚。翻译如下：

错误：不是一个 git 仓库（或者不是 .git 的父目录）

稍微解释一下啊，你这里 git log 打算查看仓库的提交历史，但是可惜 /c/test/hello4 不是一个 git 仓库。换句话说，你没有在这个目录下面执行 git init，并且也没有后续 git add，git commit，等操作。

**Comment by TristanChow** [comment]
明白了，谢谢王哥！
