### ISSUE TITLE
11.6 关注其他人

### ISSUE THREAD

**Issue by liujinmenghaoren** [wangding/courses#96]
要求如下：
 浏览并关注王顶关注的人；
或者自行在github上浏览搜索，找到自己感兴趣的并关注；

**Comment by liujinmenghaoren** [comment]
![default](https://cloud.githubusercontent.com/assets/22046197/20347057/42923af4-ac3a-11e6-9f1e-48dba190e26c.png)

### 请老师检查。  @wangding

**Comment by wangding** [comment]
可以关闭了 🍰

**Comment by liujinmenghaoren** [comment]
嗯，关了。
